### ISSUE TITLE
Could not compile libcxx: malloc/malloc.h not found

### ISSUE THREAD

**Issue by aur3l14no** [eurecom-s3/symcc#147]
SymCC is compiled successfully. But building libcxx got me these errors (during configuration).

``` bash
export SYMCC_REGULAR_LIBCXX=yes
export SYMCC_NO_SYMBOLIC_INPUT=yes

cmake -G Ninja /workspace/llvm-project/llvm \
      -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
      -DLLVM_TARGETS_TO_BUILD="X86" \
      -DLLVM_DISTRIBUTION_COMPONENTS="cxx;cxxabi;cxx-headers" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/home/vscode/libcxx_symcc \
      -DCMAKE_C_COMPILER=/workspace/symcc/build/symcc \
      -DCMAKE_CXX_COMPILER=/workspace/symcc/build/sym++
```

``` bash
/workspace/symcc/build/symcc   -O3 -DNDEBUG -o CMakeFiles/cmTC_a2a0a.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: 'malloc/malloc.h' file not found
#include <malloc/malloc.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

...
fatal error: 'mach/mach.h' file not found
fatal error: 'CrashReporterClient.h' file not found
...
```

Kindly, any advice on how to fix this error would be appreciated.

**Comment by aurelf** [comment]
I'm not sure how much the LibCXX instructions are still up to date. 
If you followed the instructions in  [docs/C++.txt](https://github.com/eurecom-s3/symcc/blob/master/docs/C%2B%2B.txt)  you used the current git version of the LLVM project? There may be breaking changes. 
Can you try compiling against LLVM-16 or 15 ? We should support those versions.

**Comment by aurelf** [comment]
An alternative is to rely on the docker files libcxx seem to work there (although I see there are issues with the symcc_fuzzing_helper but this is another problem)

**Comment by aurelf** [comment]
No problem, I'll close it for now, let us know if you succeed to build the libcxx with SymCC.
