### ISSUE TITLE
Requesting example of running symcc with symbolic input file

### ISSUE THREAD

**Issue by AndrewQuijano** [eurecom-s3/symcc#166]
I was hoping to get familiar with using symcc, but with files. I see the option to set an environment variable to have an input file. However, when I built this executable locally, I am not getting any results. What am I doing wrong such that I am not getting more results? How would I get this working with the concolic script?

![image](https://github.com/eurecom-s3/symcc/assets/13652675/be0a570e-277e-48c3-aa2a-c84d9e2ea34f)

Here is the code

`#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>
#include <fcntl.h>

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s inputfile\n", argv[0]);
        return 1;
    }
    int fd = open(argv[1], O_RDONLY);
    char buf[64] = {};
    int r = read(fd, buf, 64);
    if (r < 5) {
        fprintf(stderr, "Need at least five characters of input\n");
        return 1;
    }
    buf[63] = '\0';
    if (buf[0] == 'h' && buf[1] == 'e' && buf[2] == 'l' && buf[3] == 'l' && buf[4] == 'o') {
        printf("Bug!!\n");
        return 1;
    }
    else {
        printf("%s\n", buf);
        return 0;
    }
}`

**Comment by AndrewQuijano** [comment]
Actually, realized it seems my issue was the length does not change

**Comment by AndrewQuijano** [comment]
![image](https://github.com/eurecom-s3/symcc/assets/13652675/e46fc00e-af03-45b6-9fc5-288463ddee54)

**Comment by AndrewQuijano** [comment]
Then I would use `../util/pure_concolic_execution.sh -i ./input/ -o ./output/ ./test_file @@` to have my program run with concolic execution

**Comment by sebastianpoeplau** [comment]
That's correct, SymCC doesn't change the length of your input. With C and C++ strings you can often work around this limitation by creating a relatively large input file and relying on SymCC to put a null character in the right place to terminate the string early. (In that sense, SymCC can shorten the input...)
