### ISSUE TITLE
symCC not working against sample.cpp

### ISSUE THREAD

**Issue by straightblast** [eurecom-s3/symcc#25]
Hi,

So i successfully built symcc and sym++ using llvm-8. I use the instructions from docker file to and manually compiled each piece. Everything appears to be compiled successfully.

When I tried to play with the sample.cpp, i followed the instruction and did "sym++ sample.cpp -o sample"
I ran the sample binary as follows:
"echo 'aaaa' | ./sample"
I got the following stdout:

This is SymCC running with the QSYM backend
Performing fully concrete execution (i.e., without symbolic input)
What's your name?
Hello, aaaa!
root@symcc:/opt# ls -al /tmp/output/
total 8
drwxr-xr-x 2 root root 4096 Sep 27 12:54 .
drwxrwxrwt 1 root root 4096 Sep 27 12:54 ..

According to the main github page for this project. There should be something in the /tmp/output folder, but I did not see anything after executing the sample binary.

Any suggestions?

Thank you.

**Comment by sebastianpoeplau** [comment]
There should be indeed :) Let me check...

**Comment by sebastianpoeplau** [comment]
@straightblast could you give me some more information on your setup? Which Linux distribution are you using? Maybe I can reproduce the problem with a container or VM of the same distribution. I just fixed the Docker container (#22) and the sample works, but the container is now using LLVM 10...
