### ISSUE TITLE
symcc: No output for openjpeg example

### ISSUE THREAD

**Issue by break2make** [eurecom-s3/symcc#28]
After built of openjpeg, I have followed the following steps to start symbolic execution:
```
ubuntu@a7235eb2816d:~$ export SYMCC_INPUT_FILE='/tmp/file1.jp2'
ubuntu@a7235eb2816d:~$ unset SYMCC_NO_SYMBOLIC_INPUT 
ubuntu@a7235eb2816d:~$ echo $SYMCC_INPUT_FILE                 
/tmp/file1.jp2
ubuntu@a7235eb2816d:~$ sudo /tmp/openjpeg/build/bin/opj_decompress -i @@ -o /tmp/output/image.pgm

This is SymCC running with the QSYM backend
Reading program input until EOF (use Ctrl+D in a terminal)...
```
If I run the program without sudo:
```
ubuntu@a7235eb2816d:~$ /tmp/openjpeg/build/bin/opj_decompress -i @@ -o /tmp/output/image.pgm
This is SymCC running with the QSYM backend
Making data read from /tmp/file1.jp2 as symbolic
!! infile cannot be read: @@ !!
```

**Query:**
Is it working? Program is waiting here for long time. Is the program waiting for input from stdin? Any suggestion.

**Comment by sebastianpoeplau** [comment]
Hi @break2make,

Using `@@` as a placeholder for the input file is only supported via the fuzzing helper. When you want to run SymCC on a single input, just replace `@@` with the actual name of the file:

```
$ /tmp/openjpeg/build/bin/opj_decompress -i /tmp/file1.jp2 -o /tmp/output/image.pgm
```

Hope this helps!

**Comment by break2make** [comment]
Yes, it works.
Thank you.
