### ISSUE TITLE
Wishlist: secondary fuzzer instance like eclipser 2.0

### ISSUE THREAD

**Issue by vanhauser-thc** [eurecom-s3/symcc#36]
eclipser 2.0 (https://github.com/SoftSec-KAIST/Eclipser#eclipser-v20) now does not its own fuzzing anymore and "just" tried to find new paths by concolic execution, basically what symcc does, but already as a ready-made tool to just just as an afl-fuzz -S secondary.

This feature is seriously missing for symcc, and would spread and improve it's usage.
my assumption is that the symcc is faster and better than eclipser so this would really be a great step forward.

**Comment by sebastianpoeplau** [comment]
Hi @vanhauser-thc,

I haven't tried the new Eclipser feature yet, but we have `symcc_fuzzing_helper` to run SymCC just like a secondary AFL instance (see https://github.com/eurecom-s3/symcc/blob/master/docs/Fuzzing.txt). How is that different from what you have on your wish list?

**Comment by vanhauser-thc** [comment]
I wasnt aware that this existed ... uh ... forget it ;)
