### ISSUE TITLE
Missing build dependencies in README

### ISSUE THREAD

**Issue by SweetVishnya** [eurecom-s3/symcc#47]
Hi!

It would be nice to list all build dependencies in README. Like `lit` and so on.

**Comment by sebastianpoeplau** [comment]
Yes, we should probably mention `lit`. Did you find anything else that is required but not mentioned?

**Comment by SweetVishnya** [comment]
I do not remember( you can check the Dockerfile

**Comment by aurelf** [comment]
Closed by 9b20609
