### ISSUE TITLE
Build backend error

### ISSUE THREAD

**Issue by juhao-code** [eurecom-s3/symcc#59]
Hello,there is a problem when i build the backend 

-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/local/bin/clang-10
-- Check for working C compiler: /usr/local/bin/clang-10 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-10
-- Check for working CXX compiler: /usr/bin/clang++-10 -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/usr/bin/clang++-10"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/suiyize/symcc_source/symcc_build_simple/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_e79ec && [1/2] Building CXX object CMakeFiles/cmTC_e79ec.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_e79ec.dir/testCXXCompiler.cxx.o 
    /usr/bin/clang++-10     -o CMakeFiles/cmTC_e79ec.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
    : CommandLine Error: Option 'help-list' registered more than once!
    LLVM ERROR: inconsistency in registered CommandLine options
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)

-- Configuring incomplete, errors occurred!
See also "/home/suiyize/symcc_source/symcc_build_simple/CMakeFiles/CMakeOutput.log".
See also `"/home/suiyize/symcc_source/symcc_build_simple/CMakeFiles/CMakeError.log".`

and the command is 
CC=clang-10 CXX=clang++-10 cmake -G Ninja     -DQSYM_BACKEND=OFF     -DCMAKE_BUILD_TYPE=RelWithDebInfo     -DZ3_TRUST_SYSTEM_VERSION=on     -DLLVM_DIR=/usr/lib/llvm-10/cmake ~/symcc_source && ninja check

**Comment by sebastianpoeplau** [comment]
Is your `clang++-10` an unmodified version? Does it work when you use it on a simple C++ test program? The error seems to be a problem with the compiler, not with SymCC: the failing command just tries to compile a CMake test program...

```
/usr/bin/clang++-10     -o CMakeFiles/cmTC_e79ec.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
```

**Comment by aurelf** [comment]
Without new input we cannot help here, closing the bug. 
Feel free to reopen with responses to the above questions.
