### ISSUE TITLE
Ninja check failed on ubuntu 18.04

### ISSUE THREAD

**Issue by harperchen** [eurecom-s3/symcc#71]
![image](https://user-images.githubusercontent.com/31884331/128518890-304e90b0-2fcc-4e2f-afff-fac9c0d0c59b.png)

**Comment by aurelf** [comment]
Can you tell us more about your environment? 
The checks are passing on the docker image.
 I cannot reproduce the problem.

**Comment by harperchen** [comment]
Hi, thanks for the prompt reply. You can reproduce this problem by changing 20.04 in Dockerfile to 18.04.

**Comment by aurelf** [comment]
Ah thanks. Is there any good reason to support older distributions ? For now this isn't a priority.
Additionally it would be nice if you identified the root cause (version ?), or provided a more detailed bug report (a stack trace, etc...).

**Comment by aurelf** [comment]
Ran some tests here, and it seems the bug report is very incomplete.  I'll close for now. Please feel free to repoen with a complete bug report (please attach full logs and modifications) and/or an explanation why ubuntu 18 should be supported or even better, a patch. 
Thanks for using SymCC!
